version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types: ["minor", "patch"]

  # Maintain dependencies for pip (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pylint-astroid:
        patterns: ["pylint", "astroid"]
      pip-dependencies:
        patterns:
          - "*"
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types: ["minor", "patch"]

  # Maintain dependencies for npm (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types: ["minor", "patch"]
